name: Linux Installer builder
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - if: runner.os == 'Linux'
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace desktop install --network-timeout 100000
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Publish
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace desktop publish-app --auth-token=${{secrets.GITHUB_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}