name: Web Installer
on:
  workflow_dispatch:
    inputs:
      cognito_url_suffix:
        description: 'Cognito URL Suffix'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
jobs:
  build:
    name: Workflow-Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace codedeploy cdk deploy --require-approval never
        env:
          COGNITO_URL_SUFFIX: ${{ inputs.cognito_url_suffix }}
          REGION: ${{ inputs.aws_region }}
          EMAIL: ${{ secrets.EMAIL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
